# Generated by Django 3.2.25 on 2026-05-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_apply_job_experience_alter_postjob_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
