# Generated by Django 3.2.25 on 2026-05-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_apply_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='interview_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='apply_job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply_job',
            name='start_location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
