# Generated by Django 3.2.25 on 2026-06-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20260526_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='vacancy',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
