# Generated by Django 3.2.25 on 2026-06-04 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_postjob_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='published_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
